.PHONY: clean
structArray: structArray.c
	gcc structArray.c -g -Wall -o structArray
dynamicStructArray: dynamicStructArray.c
	gcc dynamicStructArray.c -g -Wall -o dynamicStructArray

clean:
	@echo "cleanning project"
	-rm main *.o
	@echo "clean completed"


